version: '3'

services:
  flask_app:
    container_name: flask-web
    restart: always
    build: ./flask-web
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - "/home/ubuntu/aws_share/506-capstone/flask-web/static:/static"
    ports:
      - "80:80"
    depends_on:
      - flask_app  
